from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from .schema import canonical_json, content_sha256, load_model


COMPILER_VERSION = "0.1.0"
VARIANTS = ("technical", "typed", "semantic")


def _description(model: dict[str, Any], operation: dict[str, Any], variant: str) -> str:
    if variant == "technical":
        service = model["services"][operation["odata_binding"]["service"]]
        fields = ", ".join(parameter["technical_name"] for parameter in operation["parameters"])
        return f"GET {service['entity_set']} using OData fields: {fields}."
    if variant == "typed":
        return operation["typed_description"]

    relationship_by_id = {item["id"]: item for item in model["relationships"]}
    relation_text = " ".join(
        relationship_by_id[item]["business_description"]
        for item in operation.get("relationship_ids", [])
    )
    policy_text = "This operation reads ERP data only and never creates or changes documents."
    return " ".join(
        part for part in (operation["business_description"], relation_text, policy_text) if part
    )


def _published_name(operation: dict[str, Any], variant: str) -> str:
    return operation["technical_tool_name"] if variant == "technical" else operation["id"]


def _parameter_schema(parameter: dict[str, Any], variant: str) -> dict[str, Any]:
    result: dict[str, Any] = {"type": parameter["type"]}
    if variant == "technical":
        result["description"] = f"SAP OData field {parameter['technical_name']}."
    elif variant == "typed":
        result["description"] = parameter["typed_description"]
    else:
        result["description"] = parameter["business_description"]
    if parameter.get("pattern"):
        result["pattern"] = parameter["pattern"]
    if parameter["type"] == "string":
        result["maxLength"] = int(parameter.get("max_length", 80))
    if "minimum" in parameter:
        result["minimum"] = parameter["minimum"]
    if "maximum" in parameter:
        result["maximum"] = parameter["maximum"]
    return result


def compile_variant(model: dict[str, Any], variant: str) -> dict[str, Any]:
    if variant not in VARIANTS:
        raise ValueError(f"unknown variant {variant}")
    tools: list[dict[str, Any]] = []
    for operation in model["operations"]:
        properties: dict[str, Any] = {}
        argument_map: dict[str, str] = {}
        required: list[str] = []
        for parameter in operation["parameters"]:
            published = (
                parameter.get("technical_parameter_name", parameter["technical_name"])
                if variant == "technical"
                else parameter["name"]
            )
            properties[published] = _parameter_schema(parameter, variant)
            argument_map[published] = parameter["name"]
            if parameter.get("required"):
                required.append(published)
        input_schema: dict[str, Any] = {
            "type": "object",
            "properties": properties,
            "additionalProperties": False,
        }
        if required:
            input_schema["required"] = required
        tools.append(
            {
                "name": _published_name(operation, variant),
                "description": _description(model, operation, variant),
                "inputSchema": input_schema,
                "annotations": {"readOnlyHint": True},
                "operationId": operation["id"],
                "argumentMap": argument_map,
                "outputSchema": operation["output_schema"],
            }
        )
    artifact = {
        "artifactType": "webmcp-tool-catalog",
        "variant": variant,
        "modelId": model["model_id"],
        "modelVersion": model["model_version"],
        "compilerVersion": COMPILER_VERSION,
        "modelSha256": content_sha256(model),
        "tools": tools,
    }
    artifact["artifactSha256"] = content_sha256(artifact)
    return artifact


def _javascript(catalogs: dict[str, dict[str, Any]]) -> str:
    payload = json.dumps(catalogs, ensure_ascii=False, sort_keys=True, indent=2)
    return f"""// Generated by erp_webmcp.compiler {COMPILER_VERSION}. Do not edit by hand.
const WEBMCP_CATALOGS = {payload};

const requestedVariant = new URLSearchParams(window.location.search).get("variant") || "semantic";
const selectedCatalog = WEBMCP_CATALOGS[requestedVariant] || WEBMCP_CATALOGS.semantic;
window.__ERP_WEBMCP_CATALOG__ = selectedCatalog;
window.dispatchEvent(new CustomEvent("erp-webmcp-catalog-ready", {{ detail: selectedCatalog }}));

function canonicalArguments(tool, publishedArguments) {{
  const canonical = {{}};
  for (const [publishedName, value] of Object.entries(publishedArguments || {{}})) {{
    const canonicalName = tool.argumentMap[publishedName];
    if (canonicalName && value !== "" && value !== null && value !== undefined) {{
      canonical[canonicalName] = value;
    }}
  }}
  return canonical;
}}

async function executeTool(tool, args) {{
  const response = await fetch(`/api/tools/${{encodeURIComponent(tool.operationId)}}`, {{
    method: "POST",
    headers: {{ "Content-Type": "application/json" }},
    body: JSON.stringify(canonicalArguments(tool, args)),
  }});
  const payload = await response.json();
  if (!response.ok) throw new Error(payload.error || `HTTP ${{response.status}}`);
  return payload;
}}

async function registerSiteTools() {{
  if (typeof document.modelContext?.registerTool !== "function") {{
    window.dispatchEvent(new CustomEvent("erp-webmcp-unavailable"));
    return;
  }}
  for (const tool of selectedCatalog.tools) {{
    await document.modelContext.registerTool({{
      name: tool.name,
      description: tool.description,
      inputSchema: tool.inputSchema,
      annotations: tool.annotations,
      execute: (args) => executeTool(tool, args),
    }});
  }}
  window.dispatchEvent(new CustomEvent("erp-webmcp-ready", {{ detail: selectedCatalog }}));
}}

registerSiteTools().catch((error) => {{
  console.error("WebMCP registration failed", error);
  window.dispatchEvent(new CustomEvent("erp-webmcp-error", {{ detail: String(error) }}));
}});
"""


def build(model_path: str | Path, output_dir: str | Path) -> dict[str, Any]:
    model = load_model(model_path)
    destination = Path(output_dir)
    destination.mkdir(parents=True, exist_ok=True)
    catalogs = {variant: compile_variant(model, variant) for variant in VARIANTS}
    for variant, artifact in catalogs.items():
        (destination / f"tools.{variant}.json").write_bytes(canonical_json(artifact) + b"\n")
    (destination / "tools.generated.js").write_text(
        _javascript(catalogs), encoding="utf-8", newline="\n"
    )
    manifest = {
        "modelId": model["model_id"],
        "modelVersion": model["model_version"],
        "modelSha256": content_sha256(model),
        "compilerVersion": COMPILER_VERSION,
        "variants": {variant: catalogs[variant]["artifactSha256"] for variant in VARIANTS},
    }
    (destination / "manifest.json").write_bytes(canonical_json(manifest) + b"\n")
    return manifest


def main() -> None:
    parser = argparse.ArgumentParser(description="Compile the governed semantic model to WebMCP")
    parser.add_argument("model")
    parser.add_argument("--output", required=True)
    args = parser.parse_args()
    manifest = build(args.model, args.output)
    print(json.dumps(manifest, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
